# Generated by Django 2.0.3 on 2018-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now=True)),
                ('supply_company', models.CharField(max_length=100)),
                ('input_name', models.CharField(max_length=100)),
                ('input_car_num', models.CharField(max_length=10)),
                ('input_weight', models.FloatField()),
                ('input_actual_weight', models.FloatField()),
                ('input_discount_weight', models.FloatField()),
                ('input_time', models.TimeField(auto_now=True)),
                ('input_price', models.FloatField()),
                ('input_amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('amount_not_paid', models.FloatField()),
                ('amount_discount', models.FloatField()),
                ('confirm', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField(auto_now_add=True)),
                ('prod_name', models.CharField(max_length=100)),
                ('area_code', models.CharField(max_length=100)),
                ('floor_num', models.CharField(max_length=10)),
                ('area_code2', models.CharField(max_length=100)),
                ('floor_num2', models.CharField(max_length=10)),
                ('construction_site', models.CharField(max_length=100)),
                ('jiaozhufangshi', models.CharField(max_length=100)),
                ('strength_grade', models.CharField(max_length=100)),
                ('total_sum', models.FloatField()),
                ('sum_car_count', models.IntegerField()),
                ('begin_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('cement_content', models.FloatField()),
                ('medium_sand_content', models.FloatField()),
                ('silver_sand_content', models.FloatField()),
                ('cobblestone_content', models.FloatField()),
                ('flyash_content', models.FloatField()),
                ('water_reducer_content', models.FloatField()),
                ('breeze_content', models.FloatField()),
                ('Harborsandy_content', models.FloatField()),
                ('lushan_content', models.FloatField()),
                ('kuangjiang_content', models.FloatField()),
            ],
        ),
    ]
