# Generated by Django 2.0.3 on 2018-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputrepository',
            name='input_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='begin_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='prod_date',
            field=models.DateField(),
        ),
    ]
