# Generated by Django 2.0.3 on 2018-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_auto_20181031_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputrepository',
            options={'verbose_name': '入库', 'verbose_name_plural': '入库'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': '生产明细', 'verbose_name_plural': '生产明细'},
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='amount_discount',
            field=models.FloatField(verbose_name='优惠'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='amount_not_paid',
            field=models.FloatField(verbose_name='未付'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='amount_paid',
            field=models.FloatField(verbose_name='已付'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='confirm',
            field=models.CharField(max_length=50, verbose_name='核对否'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_actual_weight',
            field=models.FloatField(verbose_name='对方实重'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_amount',
            field=models.FloatField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_car_num',
            field=models.CharField(max_length=10, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_discount_weight',
            field=models.FloatField(verbose_name='扣吨数'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_name',
            field=models.CharField(max_length=100, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_price',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_time',
            field=models.TimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='input_weight',
            field=models.FloatField(verbose_name='重量（吨）'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='note',
            field=models.CharField(max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inputrepository',
            name='supply_company',
            field=models.CharField(max_length=100, verbose_name='供货单位'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Harborsandy_content',
            field=models.FloatField(verbose_name='港砂'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='area_code',
            field=models.CharField(max_length=100, verbose_name='区号'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='area_code2',
            field=models.CharField(max_length=100, verbose_name='区号2'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='begin_time',
            field=models.TimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='breeze_content',
            field=models.FloatField(verbose_name='矿粉用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='cement_content',
            field=models.FloatField(verbose_name='水泥用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='cobblestone_content',
            field=models.FloatField(verbose_name='石子用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='construction_site',
            field=models.CharField(max_length=100, verbose_name='施工部位'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='end_time',
            field=models.TimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='floor_num',
            field=models.CharField(max_length=10, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='floor_num2',
            field=models.CharField(max_length=10, verbose_name='楼号2'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='flyash_content',
            field=models.FloatField(verbose_name='粉煤灰用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='jiaozhufangshi',
            field=models.CharField(max_length=100, verbose_name='浇筑方式'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='kuangjiang_content',
            field=models.FloatField(verbose_name='砂浆添加剂用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='lushan_content',
            field=models.FloatField(verbose_name='鲁山河沙'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='medium_sand_content',
            field=models.FloatField(verbose_name='中砂用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='prod_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='prod_name',
            field=models.CharField(max_length=100, verbose_name='工程名称'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='silver_sand_content',
            field=models.FloatField(verbose_name='细砂用量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='strength_grade',
            field=models.CharField(max_length=100, verbose_name='强度等级'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='sum_car_count',
            field=models.IntegerField(verbose_name='累计车次'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='total_sum',
            field=models.FloatField(verbose_name='合计方量'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='water_reducer_content',
            field=models.FloatField(verbose_name='减水剂用量'),
        ),
    ]
