# Generated by Django 2.1.2 on 2018-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_auto_20181031_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='area_code2',
            field=models.CharField(max_length=100, null=True, verbose_name='区号2'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='construction_site',
            field=models.CharField(max_length=100, null=True, verbose_name='施工部位'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='floor_num2',
            field=models.CharField(max_length=10, null=True, verbose_name='楼号2'),
        ),
    ]
