# Generated by Django 2.0.3 on 2018-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0007_auto_20181101_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='area_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='区号'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='floor_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='楼号'),
        ),
    ]
